<?php
    $restaurants = [
          [
      "id"=> "1",
      "user_id"=> "1",
      "name"=> "Ristorante Doc",
      "slug"=> "ristorante-doc",
      "address"=> "via",
      "phone"=> "019637129",
      "description"=> "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean a eleifend nisl, ut mollis ex. Praesent commodo orci leo, sit amet viverra mi aliquet non. Nunc vel euismod nunc, at gravida leo. Nulla sed hendrerit lacus. Etiam at tortor sed justo pharetra vestibulum vel vitae orci. Ut rhoncus sem eget lectus viverra, luctus maximus erat vestibulum. Fusce condimentum libero ac lectus lacinia volutpat. Suspendisse ligula mi, commodo vel feugiat ac, volutpat et lacus. Morbi volutpat, nibh et tincidunt placerat, sapien leo vulputate ipsum, nec ornare erat libero vitae lorem. Etiam ullamcorper lacinia nulla, a tristique diam mollis ac. Maecenas hendrerit lorem commodo molestie imperdiet. Suspendisse placerat sodales ullamcorper. Donec tempor mattis eros at luctus.",
      "email"=> "doc@mail.com",
      "p_iva"=> "12345678910",
      "sponsored"=> "1",
      "photo"=> null,
      "photo_jumbo"=> null,
      "created_at"=> "2021-03-20 11:28:38",
      "updated_at"=> "2021-03-20 12:03:48"
    ],
    [
      "id" => "2",
      "user_id" => "1",
      "name" => "King Sushi",
      "slug" => "king-sushi",
      "address" => "via Tokio, 23",
      "phone" => "13345366",
      "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean a eleifend nisl, ut mollis ex. Praesent commodo orci leo, sit amet viverra mi aliquet non. Nunc vel euismod nunc, at gravida leo. Nulla sed hendrerit lacus. Etiam at tortor sed justo pharetra vestibulum vel vitae orci. Ut rhoncus sem eget lectus viverra, luctus maximus erat vestibulum. Fusce condimentum libero ac lectus lacinia volutpat. Suspendisse ligula mi, commodo vel feugiat ac, volutpat et lacus. Morbi volutpat, nibh et tincidunt placerat, sapien leo vulputate ipsum, nec ornare erat libero vitae lorem. Etiam ullamcorper lacinia nulla, a tristique diam mollis ac. Maecenas hendrerit lorem commodo molestie imperdiet. Suspendisse placerat sodales ullamcorper. Donec tempor mattis eros at luctus.",
      "email" => "kingSushi@mail.com",
      "p_iva" => "23454323456",
      "sponsored" => "1",
      "photo" => null,
      "photo_jumbo" => null,
      "created_at" => "2021-03-20 12:03:05",
      "updated_at" => "2021-03-20 15:36:13"
    ],
    [
      "id" => "3",
      "user_id" => "2",
      "name" => "Domino' s Pizza",
      "slug" => "domino-s-pizza",
      "address" => "indirizzo a caso",
      "phone" => "3456543234",
      "description" => "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
      "email" => "domino@mail.com",
      "p_iva" => "45675432456",
      "sponsored" => "1",
      "photo" => null,
      "photo_jumbo" => null,
      "created_at" => "2021-03-22 16:35:14",
      "updated_at" => "2021-03-22 18:53:10"
    ],
    [
      "id" => "4",
      "user_id" => "2",
      "name" => "Indiano Jones",
      "slug" => "indiano-jones",
      "address" => "indiano 141",
      "phone" => "3452343234",
      "description" => "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.",
      "email" => "indiano@mail.com",
      "p_iva" => "34564321222",
      "sponsored" => "1",
      "photo" => null,
      "photo_jumbo" => null,
      "created_at" => "2021-03-22 18:43:27",
      "updated_at" => "2021-03-22 18:45:39"
    ],
    [
      "id" => "5",
      "user_id" => "3",
      "name" => "Bun Burgers",
      "slug" => "bun-burgers",
      "address" => "Via Ranzi, 192",
      "phone" => "3497951025",
      "description" => "\"il vero hamburger di NewYork\"",
      "email" => "bun@mail.com",
      "p_iva" => "12345678922",
      "sponsored" => "1",
      "photo" => null,
      "photo_jumbo" => null,
      "created_at" => "2021-03-22 18:50:00",
      "updated_at" => "2021-03-22 18:50:00"
    ],
    [
      "id" => "6",
      "user_id" => "3",
      "name" => "Macha Poké",
      "slug" => "macha-poché",
      "address" => "Via a caso, 192",
      "phone" => "3497951025",
      "description" => "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.",
      "email" => "macha@mail.com",
      "p_iva" => "12345458922",
      "sponsored" => "1",
      "photo" => null,
      "photo_jumbo" => null,
      "created_at" => "2021-03-22 18:50:00",
      "updated_at" => "2021-03-22 18:50:00"
    ],
    [
      "id" => "7",
      "user_id" => "4",
      "name" => "Panino Giusto",
      "slug" => "panino-giusto",
      "address" => "Piazza a caso, 192",
      "phone" => "3497951025",
      "description" => "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.",
      "email" => "giusto@mail.com",
      "p_iva" => "22345458922",
      "sponsored" => "1",
      "photo" => null,
      "photo_jumbo" => null,
      "created_at"=> "2021-03-22 18:50:00",
      "updated_at" => "2021-03-22 18:50:00"
    ],
    [
      "id" => "8",
      "user_id" => "4",
      "name" => "Burrito Bar",
      "slug" => "burrito-bar",
      "address" => "Piazza a caso, 192",
      "phone" => "3497951025",
      "description" => "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.",
      "email" => "burrito@mail.com",
      "p_iva" => "22347638922",
      "sponsored" => "1",
      "photo" => null,
      "photo_jumbo" => null,
      "created_at" => "2021-03-22 18:50:00",
      "updated_at" => "2021-03-22 18:50:00"
    ],
    [
      "id" => "9",
      "user_id" => "5",
      "name" => "This Is Not A Sushi Bar",
      "slug" => "this-is-not-a-sushi-bar",
      "address" => "Piazza cinese, 192",
      "phone" => "3497951025",
      "description" => "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.",
      "email" => "burrito@mail.com",
      "p_iva" => "22097868922",
      "sponsored" => "1",
      "photo" => null,
      "photo_jumbo" => null,
      "created_at" => "2021-03-22 18:50:00",
      "updated_at" => "2021-03-22 18:50:00"
    ],
    [
        "id" => "10",
        "user_id" => "5",
        "name" => "Pescaria",
        "slug" => "pescaria",
        "address" => "Piazza pescaria, 192",
        "phone" => "3497951025",
        "description" => "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.",
        "email" => "pescaria@mail.com",
        "p_iva" => "22097868922",
        "sponsored" => "1",
        "photo" => null,
        "photo_jumbo" => null,
        "created_at" => "2021-03-22 18:50:00",
        "updated_at" => "2021-03-22 18:50:00"
    ],

    ];

    return $restaurants;
